# Dockerfile generated by GeneXus (.NET)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
LABEL maintainer="samuelitwaru <samuelitwaru@example.com>"
WORKDIR /app
COPY [".", "/app"]
ENTRYPOINT ["dotnet", "bin/GxNetCoreStartup.dll"]